I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    $ r_bond -= 1
  File "game/script.rpy", line 40, in <module>
    $ r_bond -= 1
NameError: name 'r_bond' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    $ r_bond -= 1
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 40, in <module>
    $ r_bond -= 1
NameError: name 'r_bond' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pegasus Academy - Pre-Alpha v1.0.0 1.0
Thu Jul 16 17:27:38 2020
