I'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\CLARKJR1836\\Desktop\\VN\\pegasus_academy_prealpha/game\\saves\\persistent.1594940472.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\main.py", line 581, in main
    renpy.persistent.update(True)
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\persistent.py", line 391, in update
    save()
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\persistent.py", line 407, in save
    renpy.loadsave.location.save_persistent(data)
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\savelocation.py", line 490, in save_persistent
    l.save_persistent(data)
  File "C:\Users\CLARKJR1836\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\savelocation.py", line 347, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\CLARKJR1836\\Desktop\\VN\\pegasus_academy_prealpha/game\\saves\\persistent.1594940472.tmp'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pegasus Academy - Pre-Alpha v1.0.0 1.0
Thu Jul 16 17:10:00 2020
